language: node_js
node_js:
  - "4"
matrix:
  fast_finish: true
script: "npm run test-travis && npm run lint"
after_script:
  - echo "repo_token: ${COVERALLS_REPO_TOKEN}" > .coveralls.yml
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
